server.port=8100

# Registro en el servidor de descubrimiento
eureka.client.service-url.defaultZone=http://localhost:8085/eureka/

logging.level.org.springframework.cloud.gateway=TRACE
logging.level.org.springframework.http.server.reactive=DEBUG

# --- CONFIGURACIÓN DE RUTAS (El Embudo) ---

# Ruta 1: Hacia el Master Service (Clientes, Mascotas, Personal)
spring.cloud.gateway.routes[0].id=master-service
spring.cloud.gateway.routes[0].uri=lb://clinic-master-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/master/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/api/v1/master(?<segment>/?.*), /api$\{segment}

# Ruta 2: Hacia el Auth Service (Login y Usuarios)
spring.cloud.gateway.routes[1].id=auth-service
spring.cloud.gateway.routes[1].uri=lb://clinic-auth-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/auth/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/api/v1/auth/(?<segment>.*), /$\{segment}

# Ruta 3: Hacia el =rocessor Service (Citas y Asistencia)
spring.cloud.gateway.routes[2].id=processor-service
spring.cloud.gateway.routes[2].uri=lb://clinic-processor-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/processor/**
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/api/v1/processor(?<segment>/?.*), /api$\{segment}

# --- CONFIGURACIÓN DE CORS (Para el Frontend) ---
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
# Esta propiedad le dice al Gateway que combine o elimine duplicados de CORS
spring.cloud.gateway.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

management.endpoints.web.exposure.include=gateway,refresh,health
